dashboard:
  -  id: cluster_health_{{ env }}
     title: Cluster Health -  {{ env }}
     visualIds:
       -
         id: visualization:storeserv_lagom_{{ env }}_table_of_contents
         row: 1
         col: 1
         index: 24
         size_x: 4
         size_y: 6
         delim: ','
       -
         id: visualization:akka_cluster_reachable_nodes_storeserv_lagom_{{ env }}
         row: 1
         col: 5
         index: 21
         size_x: 8
         size_y: 3
         delim: ','
       -
         id: visualization:akka_cluster_unreachable_nodes_storeserv_lagom_{{ env }}
         row: 4
         col: 5
         index: 22
         size_x: 8
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_firehose_total_ingest_rate_all_nodes_{{ env }}
         row: 7
         col: 1
         index: 11
         size_x: 12
         size_y: 3
         delim: ','

       - id: visualization:jvm_storeserv_lagom_heap_used_{{ env }}
         row: 13
         col: 1
         index: 13
         size_x: 12
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_log_rates
         row: 19
         col: 1
         index: 19
         size_x: 12
         size_y: 2
         delim: ','

      # - id: visualization:storeserv_lagom_deadletter_event_{{ env }}
      #   index: 7
      #   row: 4
      #   col: 1
      #    delim: ','

       - id: visualization:storeserv_lagom_blue_split_brain_resolver_event_{{ env }}
         row: 21
         col: 1
         index: 18
         size_x: 12
         size_y: 1
         delim: ','

       - id: visualization:storeserv_lagom_cassandra_read_counts_{{ env }}
         row: 22
         col: 1
         index: 16
         size_x: 12
         size_y: 2
         delim: ','

       - id: visualization:storeserv_lagom_cassandra_read_times_{{ env }}
         row: 22
         col: 1
         index: 16
         size_x: 12
         size_y: 2
         delim: ','

       - id: visualization:storeserv_lagom_running_actors_over_time_{{ env }}_max_count_per_bucket
         index: 11
         row: 6
         col: 1
         delim: ''
