dashboard:
  -  id: cluster_memory
     title: Cluster & Memory Dashboard
     env: [red, blue]
     visualIds:
       -
         id: cpu_load_average_{{ env }}
         index: 1
         delim: ','
       -
         id: jvm_mem_used_{{ env }}
         index: 2
         delim: ''
