dashboard:
  -  id: lagom_speeds_and_feeds_{{ env }}
     title: Lagom Speeds and Feeds -  {{ env }}
     visualIds:

       -
         id: visualization:storeserv_lagom_{{ env }}_table_of_contents
         row: 1
         col: 1 
         index: 27
         size_x: 4
         size_y: 6
         delim: ','
       -
         id: visualization:storeserv_lagom_firehose_total_ingest_rate_all_nodes_{{ env }}
         row: 1
         col: 5 
         index: 26
         size_x: 8
         size_y: 3
         delim: ','
       -
         id: visualization:lagom_file_ingestion_rate_from_kafka_total_cinnamon_metrics_{{ env }}
         row: 13
         col: 1 
         index: 11
         size_x: 6
         size_y: 3
         delim: ','
       -
         id: visualization:storeserv_lagom_files_completely_processed_all_nodes_{{ env }}
         row: 4
         col: 5 
         index: 31
         size_x: 8
         size_y: 3
         delim: ','

       - id: visualization:lagom_monthly_file_ingestion_rate_from_kafka_total_cinnamon_metrics_{{ env }}
         row: 13
         col: 1 
         index: 11
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_files_ignored_all_nodes_{{ env }}
         row: 5
         col: 7 
         index: 32
         size_x: 8
         size_y: 3
         delim: ','

       - id: visualization:lagom_output_rate_{{ env }}_total
         row: 16
         col: 1 
         index: 6
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:lagom_data_ingestion_rate_from_kafka_total_cinnamon_metrics_{{ env }}
         row: 13
         col: 7 
         index: 10
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:average_file_immigration_age_{{ env }}
         row: 19
         col: 1 
         index: 28
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_log_rates
         index: 10
         row: 5
         col: 7
         delim: ''
