dashboard:
  -  id: storeserv_lagom_jvm_{{ env }}
     title: StoreServ Lagom JVM - {{ env }}
     visualIds:

       -
         id: visualization:storeserv_lagom_{{ env }}_table_of_contents
         row: 1
         col: 1
         index: 17
         size_x: 4
         size_y: 3
         delim: ','
       -
         id: visualization:jvm_storeserv_lagom_heap_used_{{ env }}
         row: 1
         col: 5
         index: 11
         size_x: 8
         size_y: 3
         delim: ','

#       -
#        id: visualization:jvm_storeserv_lagom_heap_used_{{ env }}
#         index: 3
#         row: 2
#         col: 1
#         delim: ','

       - id: visualization:jvm_storeserv_lagom_max_heap_{{ env }}
         row: 4
         col: 7
         index: 12
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:jvm_storeserv_lagom_young_gc_counts_{{ env }}
         row: 7
         col: 1
         index: 18
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:jvm_storeserv_lagom_young_gc_times_{{ env }}
         row: 7
         col: 7
         index: 19
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:jvm_storeserv_lagom_old_gc_counts_{{ env }}
         row: 10
         col: 7
         index: 21
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:jvm_storeserv_lagom_old_gc_times_{{ env }}
         row: 10
         col: 1
         index: 22
         size_x: 6
         size_y: 3
         delim: ''
