dashobard:
  -  id: storeserv_elasticsearch_push_{{ env }}
     title: StorServ Elasticsearch Push -  {{ env }}
     visualIds:

       -
         id: visualization:storeserv_lagom_{{ env }}_table_of_contents
         index: 1
         row: 1
         col: 1
         delim: ','
       -
         id: visualization:storeserv_elasticsearch_push_rate_system_objects_{{ env }}
         index: 2
         row: 1
         col: 7
         delim: ','
       -
         id: visualization:storeserv_elasticsearch_push_monthly_systems_{{ env }}
         index: 3
         row: 2
         col: 1
         delim: ','
       -
         id: visualization:storeserv_elasticsearch_push_current_systems_{{ env }}
         index: 4
         row: 2
         col: 7
         delim: ','

       - id: visualization:storeserv_elasticsearch_push_version_recommendations_{{ env }}
         index: 5
         row: 3
         col: 1
         delim: ','

       - id: visualization:storeserv_elasticsearch_push_notifications_{{ env }}
         index: 6
         row: 3
         col: 7
         delim: ','

       - id: visualization:storeserv_elasticsearch_push_others_{{ env }}
         index: 7
         row: 4
         col: 1
         delim: ','

       - id: visualization:storeserv_elasticsearch_frontend_system_object_split_rate_{{ env }}
         index: 8
         row: 4
         col: 7
         delim: ','

       - id: visualization:storeserv_elasticsearch_frontend_notification_status_split_rate_{{ env }}
         index: 9
         row: 5
         col: 1
         delim: ','

       - id: visualization:jvm_storeserv_elasticsearch_push_heap_used_{{ env }}
         index: 10
         row: 5
         col: 7
         delim: ','

       - id: visualization:jvm_storeserv_elasticsearch_push_old_gc_counts_{{ env }}
         index: 11
         row: 6
         col: 1
         delim: ','

       - id: visualization:storeserv_es_push_{{ env }}_current_data_point_front_end_processing_times
         index: 12
         row: 6
         col: 7
         delim: ''

