dashboard:
  -  id: storeserv_lagom_{{ env }}_serialization_times
     title: Storeserv Lagom Serialization Times -  {{ env }}
     visualIds:

       -
         id: visualization:storeserv_lagom_{{ env }}_table_of_contents
         row: 1
         col: 1 
         index: 5
         size_x: 4
         size_y: 4
         delim: ','

       -
         id: visualization:storeserv_lagom_{{ env }}_systemfilesactor_message_processing_time_milliseconds
         row: 1
         col: 5 
         index: 7
         size_x: 8
         size_y: 4
         delim: ','
       -
         id: visualization:storeserv_lagom_{{ env }}_systemdatapoint_serialization_time
         row: 5
         col: 1 
         index: 4
         size_x: 6
         size_y: 3
         delim: ','
       -
         id: visualization:storeserv_lagom_{{ env }}_system_files_actor_state_serialization_time
         row: 5
         col: 7
         index: 3
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_casenotification_serialization_time
         index: 5
         row: 3
         col: 1
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_perform_delta_serialization_time
         index: 6
         row: 3
         col: 7
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_normal_file_parsing_time
         index: 7
         row: 4
         col: 1
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_refill_cache_file_parsing_time
         index: 8
         row: 4
         col: 7
         delim: ''
