dashboard:
  -  id: storeserv_lagom_dispatchers_{{ env }}
     title: StoreServ Lagom Dispatchers -  {{ env }}
     visualIds:

       -
         id: visualization:storeserv_lagom_{{ env }}_table_of_contents
         row: 1
         col: 1
         index: 9
         size_x: 6
         size_y: 3
         delim: ','
       -
         id: visualization:storeserv_lagom_{{ env }}_dispatchers_parallelism
         row: 1
         col: 7
         index: 5
         size_x: 6
         size_y: 3
         delim: ','
       -
         id: visualization:storeserv_lagom_{{ env }}_active_threads_max
         row: 7
         col: 1
         index: 10
         size_x: 6
         size_y: 3
         delim: ','
       -
         id: visualization:storeserv_lagom_{{ env }}_dispatchers_running_threads
         row: 4
         col: 7
         index: 2
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_active_threads_max
         row: 7
         col: 1
         index: 10
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_dispatchers_pool_size
         row: 7
         col: 7
         index: 6
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_dispatchers_max_pool_size
         row: 10
         col: 1
         index: 7
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_dispatchers_queued_tasks
         row: 10
         col: 7
         index: 4
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_dispatchers_core_pool_size
         row: 13
         col: 1
         index: 8
         size_x: 6
         size_y: 3
         delim: ','

       - id: visualization:storeserv_lagom_{{ env }}_dispatchers_processed_tasks
         row: 13
         col: 7
         index: 3
         size_x: 6
         size_y: 3
         delim: ''
