--- 
visuals: 
  -
    id: cpu_load_average
    title: CPU LOAD AVERAGE
    env: RED
    filter: '{\"meta\":{\"index\":\"Node-DEMO\",\"negate\":false,\"disabled\":false,\"alias\":null,\"type\":\"exists\",\"key\":\"node_stats.os.cpu.load_average.1m\",\"value\":\"exists\"},\"exists\":{\"field\":\"node_stats.os.cpu.load_average.1m\"},\"$state\":{\"store\":\"appState\"}}'
    index: monitoring-es-all
    Axis_Y: '{\"field\":\"node_stats.os.cpu.load_average.1m\"}'
    query: '{\"match_all\":{}}'
  -
    id: jvm_mem_used
    title: JVM MEM USED
    env: RED
    filter: '{\"meta\":{\"index\":\"Node-DEMO\",\"negate\":false,\"disabled\":false,\"alias\":null,\"type\":\"exists\",\"key\":\"node_stats.jvm.mem.heap_used_in_bytes\",\"value\":\"exists\"},\"exists\":{\"field\":\"node_stats.jvm.mem.heap_used_in_bytes\"},\"$state\":{\"store\":\"appState\"}}'
    index: monitoring-es-all
    Axis_Y: '{\"field\":\"node_stats.jvm.mem.heap_used_in_bytes\"}'
    query: '{\"match_all\":{}}'

  - id: cpu_load_average
    title: CPU LOAD AVERAGE
    env: BLUE
    filter: '{\"meta\":{\"index\":\"Node-DEMO\",\"negate\":false,\"disabled\":false,\"alias\":null,\"type\":\"exists\",\"key\":\"node_stats.os.cpu.load_average.1m\",\"value\":\"exists\"},\"exists\":{\"field\":\"node_stats.os.cpu.load_average.1m\"},\"$state\":{\"store\":\"appState\"}}'
    index: monitoring-es-all
    Axis_Y: '{\"field\":\"node_stats.os.cpu.load_average.1m\"}'
    query: '{\"match_all\":{}}'

  - id: jvm_mem_used
    title: JVM MEM USED
    env: BLUE
    filter: '{\"meta\":{\"index\":\"Node-DEMO\",\"negate\":false,\"disabled\":false,\"alias\":null,\"type\":\"exists\",\"key\":\"node_stats.jvm.mem.heap_used_in_bytes\",\"value\":\"exists\"},\"exists\":{\"field\":\"node_stats.jvm.mem.heap_used_in_bytes\"},\"$state\":{\"store\":\"appState\"}}'
    index: monitoring-es-all
    Axis_Y: '{\"field\":\"node_stats.jvm.mem.heap_used_in_bytes\"}'
    query: '{\"match_all\":{}}'