---
visuals:
  -
    id: cpu_load_average_red
    title: CPU LOAD AVERAGE
    env: RED
    filter: '{\"meta\": {\"index\": \"Node-DEMO\", \"value\": \"exists\", \"disabled\": false, \"alias\": null, \"key\": \"node_stats.os.cpu.load_average.1m\", \"negate\": false, \"type\": \"exists\"}, \"$state\": {\"store\": \"appState\"}, \"exists\": {\"field\": \"node_stats.os.cpu.load_average.1m\"}}'
    index: monitoring-es-all
    Axis_Y: '{\"field\": \"node_stats.os.cpu.load_average.1m\"}'
    query: '{\"match_all\": {}}'
        
  -
    id: jvm_mem_used_red
    title: JVM MEM USED
    env: RED
    filter: '{\"meta\": {\"index\": \"Node-DEMO\", \"value\": \"exists\", \"disabled\": false, \"alias\": null, \"key\": \"node_stats.jvm.mem.heap_used_in_bytes\", \"negate\": false, \"type\": \"exists\"}, \"$state\": {\"store\": \"appState\"}, \"exists\": {\"field\": \"node_stats.jvm.mem.heap_used_in_bytes\"}}'
    index: monitoring-es-all
    Axis_Y: '{\"field\": \"node_stats.jvm.mem.heap_used_in_bytes\"}'
    query: '{\"match_all\": {}}'
        
  -
    id: cpu_load_average_blue
    title: CPU LOAD AVERAGE
    env: BLUE
    filter: '{\"meta\": {\"index\": \"Node-DEMO\", \"value\": \"exists\", \"disabled\": false, \"alias\": null, \"key\": \"node_stats.os.cpu.load_average.1m\", \"negate\": false, \"type\": \"exists\"}, \"$state\": {\"store\": \"appState\"}, \"exists\": {\"field\": \"node_stats.os.cpu.load_average.1m\"}}'
    index: monitoring-es-all
    Axis_Y: '{\"field\": \"node_stats.os.cpu.load_average.1m\"}'
    query: '{\"match_all\": {}}'
        
  -
    id: jvm_mem_used_blue
    title: JVM MEM USED
    env: BLUE
    filter: '{\"meta\": {\"index\": \"Node-DEMO\", \"value\": \"exists\", \"disabled\": false, \"alias\": null, \"key\": \"node_stats.jvm.mem.heap_used_in_bytes\", \"negate\": false, \"type\": \"exists\"}, \"$state\": {\"store\": \"appState\"}, \"exists\": {\"field\": \"node_stats.jvm.mem.heap_used_in_bytes\"}}'
    index: monitoring-es-all
    Axis_Y: '{\"field\": \"node_stats.jvm.mem.heap_used_in_bytes\"}'
    query: '{\"match_all\": {}}'
        